@startuml Componentes y paquetes

top to bottom direction

package es.etg.prog.galeria.view{
    component View <<FXML file>>
    component ViewController <<java>>
}

package es.etg.prog.galeria.controller{
    component GaleriaController <<java>>

    () "IGaleria" as IGA

    GaleriaController ..|> IGA 

}

ViewController ..|> IGA
ViewController ..> View: use

package es.etg.prog.galeria.model{
    component BBDD << SQLite >>
    component Fichero << XML >>

    () "BBDDDAO" as BDDAO
    () "FicheroDAO" as FDAO

    BBDD ..|> BDDAO 
    Fichero ..|> FDAO 
}

GaleriaController ..|> BDDAO 
GaleriaController ..|> FDAO 

@enduml