@startuml arquitectura

top to bottom direction

component Vista << JavaFx >>
component Controlador << Java >>
component Modelo << SQLite y XML >>

() "GaleriaController" as GC
() "BBDD Data Access" as BD
() "XML Data Access" as XM

Vista ..> GC: use
Controlador -- GC
Modelo -- BD
Modelo -- XM
Controlador ..> BD: use
Controlador ..> XM: use

@enduml